# Apated from wmt14_en_de.yaml, see https://opennmt.net/OpenNMT-py/examples/Translation.html
# also https://github.com/OpenNMT/OpenNMT-py/blob/master/config/config-transformer-base-1GPU.yml

save_data: data/
## Where the vocab(s) will be written
src_vocab: data/opennmt_vocab.sign+
tgt_vocab: data/opennmt_vocab.spm.en
src_feats_vocab: 
    feat_col: data/opennmt_vocab.feat_col
    feat_row: data/opennmt_vocab.feat_row
    feat_x: data/opennmt_vocab.feat_x
    feat_y: data/opennmt_vocab.feat_y

# Corpus opts:
data:
    train:
        path_src: data/train.withDict.sign+
        path_tgt: data/train.withDict.spm.en
        src_feats:
            feat_col: data/train.sign+.feat_col
            feat_row: data/train.sign+.feat_row
            feat_x: data/train.sign+.feat_x
            feat_y: data/train.sign+.feat_y
        transforms: [filterfeats, inferfeats, filtertoolong]
    valid:
        path_src: data/dev.sign+
        path_tgt: data/dev.spm.en
        src_feats:
            feat_col: data/dev.sign+.feat_col
            feat_row: data/dev.sign+.feat_row
            feat_x: data/dev.sign+.feat_x
            feat_y: data/dev.sign+.feat_y
        transforms: [filterfeats, inferfeats, filtertoolong]

### Transform related opts:
#### Subword
# tgt_subword_model: data/opennmt_subword.model
# tgt_subword_nbest: 1
# tgt_subword_alpha: 0.0
#### Filter
src_seq_length: 500
tgt_seq_length: 500

# silently ignore empty lines in the data
skip_empty_level: silent

# General opts
save_model: models_opennmt/sign+2en/model
keep_checkpoint: 10
save_checkpoint_steps: 3000
average_decay: 0.0005
seed: 1234
report_every: 100
train_steps: 80000
valid_steps: 1000

# Batching
# queue_size: 10000
# bucket_size: 32768
world_size: 1
gpu_ranks: [0]
batch_type: "sents"
batch_size: 32
valid_batch_size: 32
batch_size_multiple: 1
max_generator_batches: 0
accum_count: [3]
accum_steps: [0]

# Optimization
model_dtype: "fp32"
optim: "adam"
learning_rate: 2
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "sents"

# Model
encoder_type: transformer
decoder_type: transformer
enc_layers: 6
dec_layers: 6
heads: 8
rnn_size: 512
feat_vec_size: 16
feat_merge: "concat"
src_word_vec_size: 448
tgt_word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]
share_decoder_embeddings: true
share_embeddings: false

# Early stopping
# early_stopping: 5
# early_stopping_criteria: 'ppl'